import { Inter } from "next/font/google";
import styles from "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RRA Group Header",
  description: "Generated by create next app",
};

export default function HeadersLayout({ children }) {
  return (
    <>
      <header className={styles.header}>
        <h1>{metadata.title}</h1>
        <p>{metadata.description}</p>
      </header>
    </>
  );
}
